// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghfkfnyeugblsiqswzdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoZmtmbnlldWdibHNpcXN3emRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzM4NTMsImV4cCI6MjA2NzQwOTg1M30.1X2Q1sBBnPrxaQBKdVnD2TlyjDJ7IXMy7D0CljmxcQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});